# Generated by Django 3.0.6 on 2020-09-29 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200929_0052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article_URL',
        ),
    ]
