# Generated by Django 3.0.6 on 2020-10-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_delete_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscriber_id',
            field=models.CharField(max_length=16),
        ),
    ]
