# Generated by Django 3.0.6 on 2020-10-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20201001_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber_ID',
        ),
    ]
