# Generated by Django 3.0.6 on 2020-10-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_delete_subscriber_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
